Fosology playbook Authored
Be-Secure/besecure-playbooks-store pull request #28
Opened 2024-03-05 08:34 UTC by samirparhi-dev

Fosology playbook Authored Please review

2024-03-07 03:54 UTC, asa1997 commented on playbooks/besman-fossology_license_compliance-playbook.sh
> +    FOSSOLOGY_HOST_URL_WITH_PORT_NO="$2"
Move the actual execution into a steps file.

2024-03-07 03:55 UTC, asa1997 commented on playbooks/besman-fossology_license_compliance-playbook.sh
> +    sleep 10
Why is this required?

2024-03-07 03:55 UTC, asa1997 commented on playbooks/besman-fossology_license_compliance-playbook.sh
> +    if [ $? -eq 0 ]; then
This checks for sleep and not the docker stop command

2024-03-07 03:56 UTC, asa1997 requested changes
@samirparhi-dev Please look at the comments. Update the metadata json file

2024-03-22 05:14 UTC, pramit-d requested changes
@samirparhi-dev Please add a version for playbooks. The file name should contain the version number. Remove sync, codeql, and sonar-scanner playbook files from this PR as they are already added in another PR.
Use [sbom generator](https://github.com/Be-Secure/besecure-playbooks-store/blob/main/playbooks/besman-spdx-sbom-generator-0.0.1-playbook.sh) playbook as an example, and modify the file accordingly.

2024-03-26 06:39 UTC, closed without merging