adjusted sonar scanner playbook and created from main branch.
Be-Secure/besecure-playbooks-store pull request #37
Opened 2024-04-25 07:14 UTC by samirparhi-dev

please merge it if it is okay

2024-04-25 07:17 UTC, asa1997 requested changes
@samirparhi-dev Please address the change

2024-04-25 07:17 UTC, asa1997 commented on playbooks/besman-sast-sonarqube-0.0.1-playbook.sh
Please rename the file name to besman-sonarqube-0.0.1-playbook.sh

2024-04-25 07:56 UTC, samirparhi-dev commented on playbooks/besman-sast-sonarqube-0.0.1-playbook.sh
done

2024-04-25 08:32 UTC, asa1997 requested changes

2024-04-25 15:44 UTC, samirparhi-dev commented on playbook-metadata.json
> +      "name": "sonar_scanner",
Plz you do the changes, I will be not be able do the minor changes. Else assignment some one else to do these changes. Until unless there is a common understanding and clarity on documentation I can not do it again and again.

2024-04-25 15:44 UTC, samirparhi-dev commented on playbooks/besman-sonarqube-0.0.1-playbook.sh
> +    export ASSESSMENT_TOOL_PLAYBOOK="besman-$ASSESSMENT_TOOL_TYPE-$ASSESSMENT_TOOL_NAME-playbook.sh"
Plz you do the changes, I will be not be able do the minor changes. Else assignment some one else to do these changes. Until unless there is a common understanding and clarity on documentation I can not do it again and again.

2024-04-25 15:44 UTC, samirparhi-dev commented on playbooks/besman-sonarqube-0.0.1-playbook.sh
> +    export steps_file_name="besman-$ASSESSMENT_TOOL_TYPE-$ASSESSMENT_TOOL_NAME-steps.md"
Plz you do the changes, I will be not be able do the minor changes. Else assignment some one else to do these changes. Until unless there is a common understanding and clarity on documentation I can not do it again and again.

2024-04-25 15:44 UTC, samirparhi-dev commented on playbooks/besman-sonarqube-0.0.1-playbook.sh
> +    [[ ! -f $BESMAN_TOOL_PATH/$ASSESSMENT_TOOL_NAME ]] && __besman_echo_red "Could not find artifact @ $BESMAN_TOOL_PATH/$ASSESSMENT_TOOL_NAME" && flag=true
Plz you do the changes, I will be not be able do the minor changes. Else assignment some one else to do these changes. Until unless there is a common understanding and clarity on documentation I can not do it again and again.

2024-04-26 05:11 UTC, asa1997 commented
@samirparhi-dev These errors were found out when I executed your playbook. You should have an understanding on how these scripts work, only then you could avoid these minor changes. If you had any queries, you could have asked them before you raised the pr or before you started working on these and its not ethical to drop something, which was  assigned to you, soo close to the deadline.

So, I kindly request you to finish the task assigned to you on time.

@panickervinod @sumodgeorge @harimohanr

2024-04-26 09:34 UTC, samirparhi-dev commented
@sumodgeorge <https://github.com/sumodgeorge> : Kindly have a look in to
below points accordance to above reply:

- As per the above reply from the maintainer, The open source Community
trying to teach me ethics where they don't follow it. Few Examples:
                   - There is no process defined or documented
                   - The design spec is not documented any where. Whatever
comes to the mind to the maintainer , he thinks that that is a feature
without taking approval from community member.
                 - Release happens whenever they want
                 - Reluctant to adopt changes
- This tool does not have compatibility.
        Example:
          - This tool is claimed to be only designed to works on Ubuntu. I
have multiple times iterated we have verity of OS  still the maintainer
expect me to perform test before commits.
            - In the same line I have highlighted  our team uses a wide
range of OS, so the maintainer needs an approval while doing release which
is not taken care of yet.
         -
          - Maintainer is reluctant to make even small changes which need a
little effort and expect to be done by the original commuter which shows
they are not very serious about features.

Currently I have more other priorities to work on rather than contributing
to this kind of an Community which is very much monotonous

 @panickervinod <https://github.com/panickervinod>   @harimohanr
<https://github.com/harimohanr>   FYI
-----------------------------------------------------------------------
*Samir Ranjan Parhi*
*Email:* ***@***.***
*Website:* https://ls-lrt.com
*GitHub:* https://github.com/samirparhi-dev
*LinkedIn:* https://www.linkedin.com/in/samir-parhi


On Fri, Apr 26, 2024 at 10:41 AM Arun Suresh ***@***.***>
wrote:

> @samirparhi-dev <https://github.com/samirparhi-dev> These errors were
> found out when I executed your playbook. You should have an understanding
> on how these scripts work, only then you could avoid these minor changes.
> If you had any queries, you could have asked them before you raised the pr
> or before you started working on these and its not ethical to drop
> something, which was assigned to you, soo close to the deadline.
>
> So, I kindly request you to finish the task assigned to you on time.
>
> @panickervinod <https://github.com/panickervinod> @sumodgeorge
> <https://github.com/sumodgeorge> @harimohanr
> <https://github.com/harimohanr>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Be-Secure/besecure-playbooks-store/pull/37#issuecomment-2078643326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOJWVYEBJ3RZXMFPW3FMCZLY7HOXXAVCNFSM6AAAAABGYI6C5KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZYGY2DGMZSGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-08 07:18 UTC, harimohanr commented
@samirparhi-dev We have reused some of the files you have implemented and merged it into develop branch in a seperate PR. Closing this PR as it is stale currently. Thanks Samir for this contribution.

2024-05-08 07:18 UTC, closed without merging